import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

export interface TrainConfig {
  /** Path to base model or HuggingFace model ID */
  baseModel: string;
  /** Path to JSONL training dataset */
  dataset: string;
  /** Directory to save the LoRA adapter */
  outputDir: string;
  /** Training backend */
  backend: 'unsloth' | 'axolotl';
  /** Number of training epochs */
  epochs?: number;
  /** LoRA rank (default 16) */
  rank?: number;
  /** Learning rate (default 2e-4) */
  lr?: number;
}

export interface TrainingResult {
  success: boolean;
  adapter_path?: string;
  adapter_size_mb?: number;
  epochs_completed?: number;
  error?: string;
}

/**
 * Run LoRA training via Python subprocess.
 *
 * Requires Python 3.10+ and the chosen backend installed:
 * - unsloth: pip install unsloth
 * - axolotl: pip install axolotl
 */
export function trainLoRA(config: TrainConfig): TrainingResult {
  const {
    baseModel,
    dataset,
    outputDir,
    backend,
    epochs = 3,
    rank = 16,
    lr = 2e-4,
  } = config;

  // Validate inputs
  if (!existsSync(dataset)) {
    return { success: false, error: `Dataset not found: ${dataset}` };
  }

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Generate training script
  const script = backend === 'unsloth'
    ? generateUnslothScript(baseModel, dataset, outputDir, epochs, rank, lr)
    : generateAxolotlConfig(baseModel, dataset, outputDir, epochs, rank, lr);

  const scriptPath = join(outputDir, backend === 'unsloth' ? 'train.py' : 'config.yml');
  writeFileSync(scriptPath, script, 'utf-8');

  try {
    if (backend === 'unsloth') {
      execSync(`python3 ${scriptPath}`, {
        cwd: outputDir,
        timeout: 3600000, // 1 hour max
        stdio: 'pipe',
      });
    } else {
      execSync(`accelerate launch -m axolotl.cli.train ${scriptPath}`, {
        cwd: outputDir,
        timeout: 3600000,
        stdio: 'pipe',
      });
    }

    const adapterPath = join(outputDir, 'adapter');
    return {
      success: true,
      adapter_path: adapterPath,
      epochs_completed: epochs,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message?.slice(0, 500) ?? 'Training failed',
    };
  }
}

function generateUnslothScript(
  model: string, dataset: string, output: string,
  epochs: number, rank: number, lr: number,
): string {
  return `#!/usr/bin/env python3
"""Auto-generated by @openclaw/become — LoRA training via Unsloth"""

from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import json, os

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="${model}",
    max_seq_length=2048,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=${rank},
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    lora_alpha=${rank * 2},
    lora_dropout=0,
    use_gradient_checkpointing="unsloth",
)

dataset = load_dataset("json", data_files="${dataset}", split="train")

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="output",
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        num_train_epochs=${epochs},
        learning_rate=${lr},
        fp16=True,
        logging_steps=1,
        output_dir="${output}/checkpoints",
        seed=42,
    ),
)

trainer.train()
model.save_pretrained("${output}/adapter")
tokenizer.save_pretrained("${output}/adapter")
print("Training complete. Adapter saved to ${output}/adapter")
`;
}

function generateAxolotlConfig(
  model: string, dataset: string, output: string,
  epochs: number, rank: number, lr: number,
): string {
  return `# Auto-generated by @openclaw/become — LoRA training via Axolotl
base_model: ${model}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_4bit: true

adapter: lora
lora_r: ${rank}
lora_alpha: ${rank * 2}
lora_dropout: 0.0
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj

datasets:
  - path: ${dataset}
    type: alpaca

sequence_len: 2048
num_epochs: ${epochs}
learning_rate: ${lr}
micro_batch_size: 2
gradient_accumulation_steps: 4

output_dir: ${output}/adapter
`;
}
