import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';

export interface TrainConfig {
  /** Path to base model or HuggingFace model ID */
  baseModel: string;
  /** Path to JSONL training dataset */
  dataset: string;
  /** Directory to save the LoRA adapter */
  outputDir: string;
  /** Training backend */
  backend: 'unsloth' | 'axolotl';
  /** Number of training epochs */
  epochs?: number;
  /** LoRA rank (default 16) */
  rank?: number;
  /** Learning rate (default 2e-4) */
  lr?: number;
}

export interface TrainingResult {
  success: boolean;
  adapter_path?: string;
  epochs_completed?: number;
  error?: string;
}

// Allowlist for safe characters in paths and model names
const SAFE_PATH_REGEX = /^[a-zA-Z0-9_\-./: ]+$/;
const SAFE_MODEL_REGEX = /^[a-zA-Z0-9_\-./]+$/;

function validateTrainInput(config: TrainConfig): string | null {
  if (!SAFE_MODEL_REGEX.test(config.baseModel)) {
    return `Invalid base model name: contains disallowed characters`;
  }
  if (!SAFE_PATH_REGEX.test(config.dataset)) {
    return `Invalid dataset path: contains disallowed characters`;
  }
  if (!SAFE_PATH_REGEX.test(config.outputDir)) {
    return `Invalid output directory: contains disallowed characters`;
  }
  if (config.epochs !== undefined && (config.epochs < 1 || config.epochs > 100)) {
    return `Epochs must be between 1 and 100`;
  }
  if (config.rank !== undefined && (config.rank < 1 || config.rank > 256)) {
    return `LoRA rank must be between 1 and 256`;
  }
  if (config.lr !== undefined && (config.lr <= 0 || config.lr > 1)) {
    return `Learning rate must be between 0 and 1`;
  }
  return null;
}

/** Escape a string for safe embedding in a Python string literal */
function escapePython(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/**
 * Run LoRA training via Python subprocess.
 *
 * Requires Python 3.10+ and the chosen backend installed:
 * - unsloth: pip install unsloth
 * - axolotl: pip install axolotl
 */
export function trainLoRA(config: TrainConfig): TrainingResult {
  const {
    baseModel,
    dataset,
    outputDir,
    backend,
    epochs = 3,
    rank = 16,
    lr = 2e-4,
  } = config;

  // Validate all inputs before any file or process operations
  const validationError = validateTrainInput(config);
  if (validationError) {
    return { success: false, error: validationError };
  }

  if (!existsSync(dataset)) {
    return { success: false, error: `Dataset not found: ${dataset}` };
  }

  const safeOutputDir = resolve(outputDir);
  if (!existsSync(safeOutputDir)) {
    mkdirSync(safeOutputDir, { recursive: true });
  }

  // Generate training script with escaped values
  const script = backend === 'unsloth'
    ? generateUnslothScript(escapePython(baseModel), escapePython(dataset), escapePython(safeOutputDir), epochs, rank, lr)
    : generateAxolotlConfig(baseModel, dataset, safeOutputDir, epochs, rank, lr);

  const scriptPath = join(safeOutputDir, backend === 'unsloth' ? 'train.py' : 'config.yml');
  writeFileSync(scriptPath, script, 'utf-8');

  try {
    if (backend === 'unsloth') {
      // Use execFileSync to avoid shell injection — passes args as array, not string
      execFileSync('python3', [scriptPath], {
        cwd: safeOutputDir,
        timeout: 3600000,
        stdio: 'pipe',
      });
    } else {
      execFileSync('accelerate', ['launch', '-m', 'axolotl.cli.train', scriptPath], {
        cwd: safeOutputDir,
        timeout: 3600000,
        stdio: 'pipe',
      });
    }

    const adapterPath = join(safeOutputDir, 'adapter');
    return {
      success: true,
      adapter_path: adapterPath,
      epochs_completed: epochs,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message?.slice(0, 500) ?? 'Training failed',
    };
  }
}

function generateUnslothScript(
  model: string, dataset: string, output: string,
  epochs: number, rank: number, lr: number,
): string {
  return `#!/usr/bin/env python3
"""Auto-generated by @openclaw/become — LoRA training via Unsloth"""

from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="${model}",
    max_seq_length=2048,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=${rank},
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    lora_alpha=${rank * 2},
    lora_dropout=0,
    use_gradient_checkpointing="unsloth",
)

dataset = load_dataset("json", data_files="${dataset}", split="train")

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="output",
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        num_train_epochs=${epochs},
        learning_rate=${lr},
        fp16=True,
        logging_steps=1,
        output_dir="${output}/checkpoints",
        seed=42,
    ),
)

trainer.train()
model.save_pretrained("${output}/adapter")
tokenizer.save_pretrained("${output}/adapter")
print("Training complete. Adapter saved to ${output}/adapter")
`;
}

function generateAxolotlConfig(
  model: string, dataset: string, output: string,
  epochs: number, rank: number, lr: number,
): string {
  return `# Auto-generated by @openclaw/become — LoRA training via Axolotl
base_model: ${model}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_4bit: true

adapter: lora
lora_r: ${rank}
lora_alpha: ${rank * 2}
lora_dropout: 0.0
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj

datasets:
  - path: ${dataset}
    type: alpaca

sequence_len: 2048
num_epochs: ${epochs}
learning_rate: ${lr}
micro_batch_size: 2
gradient_accumulation_steps: 4

output_dir: ${output}/adapter
`;
}
